USE uzaugsu_lv;

INSERT INTO popular_verses (reference, text_lv, sort_order) VALUES
('Jāņa 3:16', 'Jo tik ļoti Dievs pasauli mīlējis, ka Viņš devis Savu vienpiedzimušo Dēlu, lai neviens, kas Viņam tic, nepazustu, bet dabūtu mūžīgo dzīvību', 1),
('Psalmi 23:1', 'Tas Kungs ir mans gans, man netrūkst nekā', 2),
('Filipiešiem 4:13', 'Es visu spēju Tā spēkā, kas mani dara stipru', 3),
('Romiešiem 8:28', 'Un mēs zinām, ka tiem, kas mīl Dievu, visas lietas nāk par labu', 4),
('Jesajas 41:10', 'Nebīsties, jo Es esmu ar tevi! Neatkāpies, jo Es esmu tavs Dievs!', 5),
('Mateja 11:28', 'Nāciet šurp pie Manis visi, kas esat bēdīgi un grūtsirdīgi, Es jūs gribu atvieglināt', 6),
('Jozuas 1:9', 'Vai Es neesmu tev pavēlējis: esi stiprs un drošs, nebīsties un nebaiļojies!', 7),
('Psalmi 46:2', 'Dievs ir mūsu patvērums un spēks, palīgs bēdās, kas vienmēr ir uzticams', 8),
('2. Korintiešiem 12:9', 'Bet Viņš man sacīja: Manas žēlastības tev pietiek', 9),
('1. Korintiešiem 10:13', 'Dievs ir uzticīgs, Viņš neļaus jūs pārbaudīt pāri par jūsu spējām', 10),
('Salamana pamācības 3:5-6', 'Paļaujies uz To Kungu no visas sirds un nepaļaujies uz sava prāta gudrību', 11),
('Ebrejiem 11:1', 'Jo ticība ir stipra paļaušanās uz to, kas cerams, pārliecība par neredzamām lietām', 12),
('Jēkaba 1:12', 'Svētīgs tas vīrs, kas pastāv kārdinājumā', 13),
('Psalmi 91:11', 'Jo Viņš pavēlēs Saviem eņģeļiem tevi sargāt visos tavos ceļos', 14),
('1. Pētera 5:7', 'Visas savas rūpes uzveliet uz Viņu, jo Viņš par jums rūpējas', 15),
('Romiešiem 12:2', 'Un netopiet šai pasaulei līdzīgi, bet pārvērtieties', 16),
('Galatiešiem 5:22-23', 'Bet Gara auglis ir: mīlestība, prieks, miers, pacietība', 17),
('Efeziešiem 6:10', 'Visbeidzot: topiet stipri Kungā un Viņa varenajā spēkā', 18),
('1. Korintiešiem 16:13', 'Esiet nomodā, stāviet stipri ticībā, esiet drosmīgi, esiet stipri', 19),
('Kolosiešiem 3:23', 'Un ko jūs darāt, to dariet no sirds kā Tam Kungam', 20),
('Mateja 6:33', 'Bet meklējiet vispirms Dieva valstību un Viņa taisnību', 21),
('Jāņa 14:6', 'ES ESMU ceļš, patiesība un dzīvība', 22),
('Romiešiem 5:8', 'Bet Dievs Savu mīlestību uz mums pierāda ar to, ka Kristus par mums miris', 23),
('1. Jāņa 4:19', 'Mēs mīlam Viņu, jo Viņš mūs ir mīlējis pirmais', 24),
('Efeziešiem 2:8-9', 'Jo no žēlastības jūs esat pestīti ticībā', 25),
('2. Timotejam 1:7', 'Jo Dievs nav mums devis bailības garu, bet spēka, mīlestības un savaldības garu', 26),
('Psalmi 119:105', 'Tavs vārds ir manu kāju spīdeklis un gaišums uz maniem ceļiem', 27),
('Salamana pamācības 16:3', 'Uztici Tam Kungam savus darbus, tad tavi nodomi sekmēsies', 28),
('Mateja 5:16', 'Tāpat lai jūsu gaisma spīd cilvēku priekšā', 29),
('1. Tesaloniķiešiem 5:16-18', 'Priecājieties vienmēr, lūdziet bez mitēšanās, par visu pateicieties', 30),
('Jāņa 15:5', 'Es esmu vīnakoks, jūs esat zari', 31),
('Psalmi 37:4', 'Priecājies par To Kungu, Viņš dos tev, ko tava sirds kāro', 32),
('Romiešiem 15:13', 'Lai miera Dievs jūs piepilda ar visu prieku un mieru ticībā', 33),
('1. Korintiešiem 15:58', 'Tad nu, mani mīļie brāļi, topiet pastāvīgi, nešaubīgi', 34),
('Jēkaba 4:8', 'Tuvojieties Dievam, tad Viņš tuvojasies jums', 35),
('Psalmi 34:8', 'Nobaudiet un redziet, cik labs ir Tas Kungs', 36),
('Mateja 7:7', 'Lūdziet, tad jums taps dots; meklējiet, tad jūs atradīsit', 37),
('2. Korintiešiem 5:17', 'Tātad, ja kāds ir Kristū, tas ir jauna radība', 38),
('Ebrejiem 12:1', 'Skrienam ar pacietību to sacīksti, kas mums jāizskrien', 39),
('1. Jāņa 1:9', 'Ja atzīstamies savos grēkos, tad Viņš ir uzticīgs un taisns', 40),
('Psalmi 139:14', 'Es Tev pateicos par to, ka esmu brīnišķīgi radīts', 41),
('Romiešiem 8:38-39', 'Jo es esmu pārliecināts, ka ne nāve, ne dzīvība...', 42),
('Filipiešiem 4:6-7', 'Nebēdājiet ne par ko, bet visās lietās...', 43),
('1. Pētera 5:10', 'Bet visas žēlastības Dievs...Tas jūs pēc īsām cieŅ¡anām pats sagatavos', 44),
('Jāņa 16:33', 'To Es jums esmu sacījis, lai jums būtu miers Manī', 45),
('Salamana pamācības 18:10', 'Tā Kunga Vārds ir stipra pils', 46),
('Efeziešiem 3:20', 'Bet Tam, kas spēj darīt pāri par visu, ko mēs lūdzam', 47),
('Psalmi 27:1', 'Tas Kungs ir mana gaisma un mana pestīšana', 48),
('Mateja 28:20', 'Un redzi, Es esmu pie jums ik dienas līdz pasaules galam', 49),
('Salamana pamācības 4:23', 'Pār visu, ko tu sargi, sargi savu sirdi', 50),
('Romiešiem 12:12', 'Priecājieties cerībā, esiet pacietīgi bēdās', 51),
('1. Korintiešiem 13:4-7', 'Mīlestība ir pacietīga, mīlestība ir laipna', 52),
('Psalmi 121:1-2', 'Es paceļu savas acis uz kalniem, no kurienes man nāk palīdzība', 53),
('Jesajas 40:31', 'Bet, kas paļaujas uz To Kungu, tie dabū jaunu spēku', 54),
('2. Korintiešiem 4:16', 'Tāpēc mēs nepiekūstam, bet...mūsu iekšējais dienu no dienas atjaunojas', 55),
('Ebrejiem 13:5', 'Es tevi neatstāšu un tevi nepametīšu', 56),
('Jāņa 10:10', 'Es esmu nācis, lai tiem būtu dzīvība un lai tā būtu pārpilnībā', 57),
('1. Timotejam 4:12', 'Neviens lai nenicina tavu jaunumu', 58),
('Psalmi 103:12', 'Cik tālu ir rīti no vakariem, tik tālu Viņš atliek mūsu pārkāpumus', 59),
('Mateja 6:34', 'Tāpēc neesiet bēdīgi par rītdienu', 60),
('Romiešiem 8:31', 'Ko lai mēs tad par to saku? Ja Dievs par mums, kas pret mums?', 61),
('Jēkaba 1:5', 'Bet, ja kādam no jums trūkst gudrības, lai lūdz no Dieva', 62),
('Psalmi 55:23', 'Met uz To Kungu savu nastu, Viņš tevi uzturēs', 63),
('1. Jāņa 4:4', 'Jūs esat no Dieva...un esat viņus uzvarējuši, jo Tas, kas ir jūsos, ir lielāks', 64),
('Efeziešiem 4:32', 'Bet esiet cits pret citu laipni un žēlsirdīgi', 65),
('Salamana pamācības 27:17', 'Dzelzs tiek ar dzelzi uzasināta, un vīrs trin vīru', 66),
('2. Tesaloniķiešiem 3:3', 'Bet Tas Kungs ir uzticīgs, Viņš jūs stiprinās', 67),
('Psalmi 42:12', 'Ko tu noskumis esi, mana dvēsele...', 68),
('1. Korintiešiem 6:19-20', 'Vai jūs nezināt, ka jūsu miesa ir Svētā Gara mājoklis', 69),
('Kolosiešiem 3:2', 'Domājiet par to, kas augšā, ne par to, kas virs zemes', 70);